"""add foreign key to Review

Revision ID: 26472b66c02a
Revises: e114e45f3f54
Create Date: 2024-07-12 19:24:38.402033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26472b66c02a'
down_revision = 'e114e45f3f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
